src/JicoDotNet.Inventory.UI/Controllers/InvoiceController.cs
using JicoDotNet.Inventory.BusinessLayer.BLL;
using JicoDotNet.Inventory.BusinessLayer.Common;
using JicoDotNet.Inventory.Core.Enumeration;
using JicoDotNet.Inventory.Core.Models;
using JicoDotNet.Inventory.UI.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using JicoDotNet.Inventory.Controllers;

namespace JicoDotNet.Inventory.UI.Controllers
{
    public class InvoiceController : BaseController
    {
        #region Invoice Type
        [SessionAuthenticate]
        public ActionResult Type()
        {
            try
            {
                InvoiceModels invoiceModels = new InvoiceModels()
                {
                    _invoiceTypes = new InvoiceLogic(LogicHelper).TypeGet()
                };
                if (!string.IsNullOrEmpty(UrlParameterId))
                {
                    invoiceModels._invoiceType = invoiceModels._invoiceTypes.Where(a => a.InvoiceTypeId == Convert.ToInt64(UrlParameterId)).FirstOrDefault();
                }
                return View(invoiceModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult Type(InvoiceType invoiceType)
        {
            try
            {
                invoiceType.InvoiceTypeId = UrlParameterId == null ? 0 : Convert.ToInt64(UrlParameterId);

                #region Data Tracking...
                DataTrackingLogicSet(invoiceType);
                #endregion

                InvoiceLogic invoiceLogic = new InvoiceLogic(LogicHelper);
                if (Convert.ToInt64(invoiceLogic.TypeSet(invoiceType)) > 0)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Success",
                        Status = true
                    };
                }
                else
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Unsuccess",
                        Status = false
                    };
                }

                return RedirectToAction("Type", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public JsonResult TypeDeactivate(string Context)
        {
            try
            {
                if (new LoginManagement(LogicHelper).Authenticate(SessionPerson.UserEmail, Context))
                {
                    InvoiceLogic invoiceLogic = new InvoiceLogic(LogicHelper);
                    long deactivateId = Convert.ToInt64(invoiceLogic.TypeDeactive(UrlParameterId));
                    return Json(new JsonReturnModels
                    {
                        _isSuccess = true,
                        _returnObject = deactivateId > 0 ? UrlParameterId : "0"
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new JsonReturnModels
                    {
                        _isSuccess = true,
                        _returnObject = "-1"
                    }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToJson(ex);
            }
        }
        #endregion

        #region Invoice Generate
        [SessionAuthenticate]
        public ActionResult Index()
        {
            try
            {
                InvoiceModels invoiceModels = new InvoiceModels()
                {
                    _invoices = new InvoiceLogic(LogicHelper).GetInvoices(),
                    _config = (new ConfigarationManager(LogicHelper)).GetConfig(),
                    _company = SessionCompany
                };
                return View(invoiceModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult Generate()
        {
            try
            {
                InvoiceModels invoiceModels = new InvoiceModels();
                InvoiceLogic invoiceLogic = new InvoiceLogic(LogicHelper);
                if (string.IsNullOrEmpty(UrlParameterId))
                {
                    invoiceModels._salesOrders = invoiceLogic.GetForEntry();
                }
                else
                {
                    // Retrive SO
                    SalesOrderLogic orderLogic = new SalesOrderLogic(LogicHelper);
                    if (invoiceLogic.GetForEntry().Where(a => a.SalesOrderId == Convert.ToInt64(UrlParameterId)).FirstOrDefault() != null)
                        invoiceModels._salesOrder = orderLogic.GetForDetail(Convert.ToInt64(UrlParameterId));

                    // -- _salesOrder Check
                    if (invoiceModels._salesOrder == null)
                    {
                        ReturnMessage = new ReturnObject()
                        {
                            Status = false,
                            Message = "Sales Order not found!"
                        };
                        return RedirectToAction("Generate", new { id = string.Empty });
                    }

                    invoiceModels._invoiceTypes = invoiceLogic.TypeGet(true);
                    invoiceModels._config = new ConfigarationManager(LogicHelper).GetConfig();
                    invoiceModels._company = SessionCompany;

                    // Checking Company is GST registred or not.
                    invoiceModels.GSTType = EGSTType.None;
                    if (invoiceModels._salesOrder.IsGstAllowed)
                    {
                        invoiceModels.GSTType = GSTLogic.GetType(invoiceModels._salesOrder.IsGSTRegistered ?
                                invoiceModels._salesOrder.GSTStateCode :
                                invoiceModels._salesOrder.StateCode,
                            SessionCompany.IsGSTRegistered ?
                                SessionCompany.GSTStateCode :
                                SessionCompany.StateCode);
                    }

                    // Previous Invoice details- if partially invoiced
                    invoiceModels._invoiceDetails = invoiceLogic.GetInvoiceDetails(Convert.ToInt64(UrlParameterId));
                    // Check previous Invoice
                    if (invoiceModels._invoiceDetails.Count > 0)
                    {
                        foreach (SalesOrderDetail salesOrderDetail in invoiceModels._salesOrder.SalesOrderDetails.ToList())
                        {
                            InvoiceDetail invDtl = invoiceModels._invoiceDetails
                                .Where(a => a.SalesOrderDetailId == salesOrderDetail.SalesOrderDetailId).FirstOrDefault();
                            if (invDtl != null)
                            {
                                if (salesOrderDetail.Quantity > invDtl.InvoicedQuantity)
                                {
                                    // This item are yet to invoiced
                                    salesOrderDetail.ShippedQuantity = invDtl.InvoicedQuantity;
                                    salesOrderDetail.Quantity -= invDtl.InvoicedQuantity;
                                }
                                else
                                {
                                    // This Item is full invoiced
                                    invoiceModels._salesOrder.SalesOrderDetails.Remove(salesOrderDetail);
                                    invoiceModels._invoiceDetails.Remove(invDtl);
                                }
                            }
                        }
                    }
                }
                return View(invoiceModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult Generate(FormCollection form, Invoice invoice)
        {
            try
            {
                // Retrive SO
                InvoiceLogic invoiceLogic = new InvoiceLogic(LogicHelper);
                SalesOrderLogic orderLogic = new SalesOrderLogic(LogicHelper);
                if (invoiceLogic.GetForEntry().FirstOrDefault(a => a.SalesOrderId == invoice.SalesOrderId) == null)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Status = false,
                        Message = "Sales Order not found!"
                    };
                    return RedirectToAction("Generate", new { id = string.Empty });
                }

                Invoice rerurnInvoice = invoiceLogic.Set(invoice, form.AllKeys.ToDictionary(key => key, value => (object)form[value]));
                if (rerurnInvoice == null || rerurnInvoice.InvoiceId < 1)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Status = false,
                        Message = "Something went Wrong!!"
                    };
                    return RedirectToAction("Generate", new { id = string.Empty });
                }
                else
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Status = true,
                        Message = "Invoice Generated!!"
                    };
                    return RedirectToAction("Detail", new { id = UrlIdEncrypt(rerurnInvoice.InvoiceId, false) });
                }
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult Detail()
        {
            try
            {
                if (string.IsNullOrEmpty(UrlParameterId))

src/JicoDotNet.Inventory.UI/Views/Invoice/Index.cshtml
@using JicoDotNet.Inventory.UI.Models;
@using JicoDotNet.Inventory.Core.Enumeration;
@model InvoiceModels


@{
    ViewBag.Title = "Invoices";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Invoice</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Invoice")"> Invoice</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-4 p-1">
                                <a href="@Url.Action("Generate", "Invoice")" class="btn btn-block btn-success"><i class="fas fa-plus"></i> Generate New Invoice</a>
                            </div>
                            <div class="col-sm-4 p-1">
                            </div>
                            <div class="col-sm-4 p-1">
                                <a href="@Url.Action("Property", "Custom", new { id = Html.UrlIdEncrypt(ECustomPropertyFor.SalesInvoice, false) })"
                                   class="btn btn-block btn-info">
                                    <i class="fas fa-align-right"></i> Set Custom Data
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title"> Invoices</h3>
                    </div>
                    <div class="card-body table-responsive" style="overflow-x:scroll;">
                        <table class="table table-striped table-bordered dt-responsive nowrap" data-table="normal">
                            <thead>
                                <tr>
                                    <th>Action</th>
                                    <th>Invoice No/Date</th>
                                    <th>Customer Name<br>GST No</th>
                                    <th>SO/Delivery No</th>
                                    <th>
                                        Invoice Amount
                                        @if (Model._company.IsGSTRegistered)
                                        {
                                            <text>/ Total </text>
                                        }
                                    </th>
                                    @if (Model._company.IsGSTRegistered)
                                    {
                                        <th>Tax</th>
                                    }
                                    <th>Vehicle/Person & Mobile</th>
                                    <th>Payment</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model._invoices != null)
                                {
                                    for (int i = 0; i < Model._invoices.Count; i++)
                                    {
                                        <tr>
                                            <td>
                                                @if (Model._invoices[i].PaymentStatus == null
                                                    || !Model._invoices[i].PaymentStatus.Value)
                                                {
                                                    <a class="btn btn-outline-danger btn-flat"
                                                       href="@Url.Action("Invoice", "Payment", new { id = Html.UrlIdEncrypt(Model._invoices[i].InvoiceId, false) })"
                                                       data-toggle="tooltip" data-placement="top" title="Receive Payment">
                                                        <i class="fas fa-money-check-alt"></i>
                                                    </a>
                                                }
                                                <a class="btn btn-outline-primary btn-flat"
                                                   href="@Url.Action("Detail", "Invoice", new { id = Html.UrlIdEncrypt(Model._invoices[i].InvoiceId, false) })"
                                                   data-toggle="tooltip" data-placement="top" title="Detail View">
                                                    <i class="fas fa-binoculars"></i>
                                                </a>
                                            </td>
                                            <td>
                                                <strong>@Model._invoices[i].InvoiceNumber</strong>
                                                @if (Model._invoices[i].IsFullInvoiced)
                                                {
                                                    <i class="fas fa-lg fa-check-square text-success" data-toggle="tooltip" title="Full Invoiced"></i>
                                                }
                                                <br />
                                                @Model._invoices[i].InvoiceDate.ToDisplayShortDateString()
                                            </td>
                                            <td>
                                                @Model._invoices[i].CompanyName
                                                <br />
                                                @if (Model._invoices[i].IsGSTRegistered)
                                                {
                                                    <em>@Model._invoices[i].GSTNumber</em>
                                                }
                                                else
                                                {
                                                    <span class="right badge badge-danger">Unregistered</span>
                                                }
                                            </td>
                                            <td>
                                                @if (string.IsNullOrEmpty(Model._invoices[i].SalesOrderNumber))
                                                {
                                                    @Model._invoices[i].ShipmentNumber
                                                }
                                                else
                                                {
                                                    @Model._invoices[i].SalesOrderNumber
                                                }
                                            </td>
                                            <td>
                                                @Model._config.CurrencySymbol@Model._invoices[i].InvoicedAmount.ToDisplayDecimal()
                                                @if (Model._company.IsGSTRegistered)
                                                {
                                                    <br />
                                                    @Model._config.CurrencySymbol@Model._invoices[i].TotalAmount.ToDisplayDecimal()
                                                }
                                            </td>
                                            @if (Model._invoices[i].IsGstApplicable && Model._company.IsGSTRegistered)
                                            {
                                                <td>
                                                    @Model._config.CurrencySymbol@Model._invoices[i].TaxAmount.ToDisplayDecimal()
                                                    <br />
                                                    @if (Model._invoices[i].GSTType == (short)EGSTType.IGST)
                                                    {
                                                        <i>IGST</i><br />
                                                    }
                                                    else if (Model._invoices[i].GSTType == (short)EGSTType.CGSTSGST)
                                                    {
                                                        <i>CGST-U/SGST </i><br />
                                                    }
                                                    else
                                                    {
                                                        <strong class="text-danger">Something wrong!! </strong><br />
                                                    }
                                                </td>
                                            }
                                            <td>
                                                @Model._invoices[i].VehicleNumber - @Model._invoices[i].HandOverPerson
                                                <br />
                                                @Model._invoices[i].HandOverPersonMobile
                                            </td>
                                            <td>
                                                @if (Model._invoices[i].PaymentStatus == null)
                                                {
                                                    <div class="progress-group">
                                                        <span class="progress-text">Not Receive</span>
                                                        <div class="progress progress-sm active" data-toggle="tooltip" title="Not received" style="border: 1px solid #28a745;">
                                                            <div class="progress-bar bg-success progress-bar-striped" style="width: 1%"></div>
                                                        </div>
                                                    </div>
                                                }
                                                else if (!Model._invoices[i].PaymentStatus.Value)
                                                {
                                                    <div class="progress-group">
                                                        <span class="progress-text">Partially Receive</span>
                                                        <div class="progress progress-sm active" data-toggle="tooltip" title="Partially received">
                                                            <div class="progress-bar bg-success progress-bar-striped" style="width: 50%"></div>
                                                        </div>
                                                    </div>
                                                }
                                                else if (Model._invoices[i].PaymentStatus.Value)
                                                {
                                                    <div class="progress-group">
                                                        <span class="progress-text">Full Received</span>
                                                        <div class="progress progress-sm active" data-toggle="tooltip" title="Full received">
                                                            <div class="progress-bar bg-success progress-bar-striped" style="width: 100%"></div>
                                                        </div>
                                                    </div>
                                                }
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/JicoDotNet.Inventory.UI/Views/Invoice/Type.cshtml
@using JicoDotNet.Inventory.UI.Models;
@using JicoDotNet.Inventory.Core.Models;
@model InvoiceModels

@{
    ViewBag.Title = "Type";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Invoice Type</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item active"><a href="@Url.Action("Type", "Invoice")">Invoice Type</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">
                            @if (Model._invoiceType != null)
                            {
                                <text> Update </text>
                            }
                            else
                            {
                                <text> Add </text>
                            }
                            Invoice Type
                        </h3>
                    </div>
                    @using (Html.BeginForm("Type", "Invoice",
                        new
                        {
                            id = ((Model._invoiceType != null) ?
                            Html.UrlIdEncrypt(Model._invoiceType.InvoiceTypeId.ToString(), false) : string.Empty)
                        },
                        FormMethod.Post, new { autocomplete = "off" }))
                    {
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Invoice Type Name</label>
                                        <input type="text" name="InvoiceTypeName" class="form-control"
                                               @if (Model._invoiceType != null) { <text> value="@(Model._invoiceType.InvoiceTypeName)" </text> }
                                               placeholder="Enter Invoice Type Name" required>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Invoice Type Details</label>
                                        <textarea name="Description" class="form-control" placeholder="Enter Invoice Type Details" style="height:38px;">@if (Model._invoiceType != null) { <text> @Model._invoiceType.Description </text>  }</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            @if (Model._invoiceType != null)
                            {
                                <button type="submit" class="btn btn-warning"> <i class="fas fa-edit"></i> Update </button>
                                <a href="@Url.Action("Type", "Invoice", new { id = string.Empty })" class="btn btn-danger"> <i class="fas fa-times"></i> Cancel</a>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-success"><i class="fas fa-save"></i> Save</button>
                            }
                            <button type="reset" class="btn btn-info"><i class="fas fa-sync"></i> Reset</button>
                        </div>
                    }
                </div>
            </div>
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">Invoice Types</h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-bordered dt-responsive nowrap" data-table="normal">
                            <thead>
                                <tr>
                                    <th>Edit/Deactivate</th>
                                    <th>Invoice Type Name</th>
                                    <th>Details</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model._invoiceTypes != null)
                                {
                                    foreach (InvoiceType invoiceType in Model._invoiceTypes)
                                    {
                                        <tr>
                                            <td>
                                                @if (invoiceType.IsActive)
                                                {
                                                    <a class="btn btn-outline-success btn-flat" href="@Url.Action("Type", "Invoice", new { id = Html.UrlIdEncrypt(invoiceType.InvoiceTypeId, false) })"
                                                       data-toggle="tooltip" data-placement="top" title="Edit">
                                                        <i class="fas fa-edit"></i>
                                                    </a>
                                                    <button onclick="DeactivateRecord(this)"
                                                            data-display="Invoice Type Name" data-value="@invoiceType.InvoiceTypeName"
                                                            data-controller="Invoice" data-action="TypeDeactivate"
                                                            data-id="@Html.UrlIdEncrypt(invoiceType.InvoiceTypeId)"
                                                            data-toggle="tooltip" data-placement="top"
                                                            class="btn btn-outline-danger btn-flat" title="Deactivate">
                                                        <i class="fas fa-trash-alt pull-right"></i>
                                                    </button>
                                                }
                                            </td>
                                            <td>@invoiceType.InvoiceTypeName</td>
                                            <td>@invoiceType.Description</td>
                                            <td>
                                                @if (invoiceType.IsActive)
                                                {
                                                    <span class="right badge badge-success">Active</span>
                                                }
                                                else
                                                {
                                                    <span class="right badge badge-danger">Inactive</span>
                                                }
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>