src/JicoDotNet.Inventory.UI/Controllers/TDSController.cs
using JicoDotNet.Inventory.BusinessLayer.BLL;
using JicoDotNet.Inventory.Core.Models;
using JicoDotNet.Inventory.UI.Models;
using System;
using System.Web.Mvc;
using JicoDotNet.Inventory.Controllers;

namespace JicoDotNet.Inventory.UI.Controllers
{
    public class TDSController : BaseController
    {
        [SessionAuthenticate]
        public ActionResult Pay()
        {
            try
            {
                TDSModels taxingModels = new TDSModels
                {
                    _tDSPays = new TaxingLogic(LogicHelper).GetTDSOuts(),
                    _config = new ConfigarationManager(LogicHelper).GetConfig(),
                    _state = GenericLogic.State()
                };
                return View(taxingModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult Pay(TDSPay tDSPay)
        {
            try
            {
                if (tDSPay.TDSPayId == Convert.ToInt64(UrlParameterId))
                {
                    if (!string.IsNullOrEmpty(new TaxingLogic(LogicHelper).SetTDSOut(tDSPay)))
                    {
                        ReturnMessage = new ReturnObject
                        {
                            Status = true,
                            Message = "TDS Payment record successfully inserted!!"
                        };
                        return RedirectToAction("Pay", new { id = string.Empty });
                    }
                }
                ReturnMessage = new ReturnObject
                {
                    Status = false,
                    Message = "Something goes wrong!!"
                };
                return RedirectToAction("Pay", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult Receive()
        {
            try
            {
                TDSModels taxingModels = new TDSModels
                {
                    _tDSReceives = new TaxingLogic(LogicHelper).GetTDSIns(),
                    _config = new ConfigarationManager(LogicHelper).GetConfig(),
                    _state = GenericLogic.State()
                };
                return View(taxingModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult Receive(TDSReceive tDSReceive)
        {
            try
            {
                if (tDSReceive.TDSReceiveId == Convert.ToInt64(UrlParameterId))
                {
                    if (!string.IsNullOrEmpty(new TaxingLogic(LogicHelper).SetTDSIn(tDSReceive)))
                    {
                        ReturnMessage = new ReturnObject
                        {
                            Status = true,
                            Message = "TDS Receive record successfully inserted!!"
                        };
                        return RedirectToAction("Receive", new { id = string.Empty });
                    }
                }
                ReturnMessage = new ReturnObject
                {
                    Status = false,
                    Message = "Something goes wrong!!"
                };
                return RedirectToAction("Receive", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }
    }
}

src/JicoDotNet.Inventory.UI/Views/TDS/Pay.cshtml
@using JicoDotNet.Inventory.UI.Models;
@model TDSModels

@{
    ViewBag.Title = "Vendor's TDS Payment";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>TDS of Vendor</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item active"><a href="@Url.Action("Pay", "TDS")">TDS</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">TDS List (unpaid)</h3>
                    </div>
                    <div class="card-body table-responsive" style="overflow-x:scroll">
                        <table class="table table-striped table-bordered dt-responsive nowrap" data-table="normal">
                            <thead style="border-top: 1px solid #dee2e6;">
                                <tr>
                                    <th>Action</th>
                                    <th>Vendor Name & Type</th>
                                    <th>PAN Number</th>
                                    <th>GST Number</th>
                                    <th>TDS</th>
                                    <th>Pay Amount</th>
                                    <th>Payment Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model._tDSPays != null)
                                {
                                    for (int i = 0; i < Model._tDSPays.Count; i++)
                                    {
                                        <tr>
                                            <td class="d-none">#@(i + 1)</td>
                                            <td style="min-width: 200px;">
                                                @using (Html.BeginForm("Pay", "TDS", new { id = Html.UrlIdEncrypt(Model._tDSPays[i].TDSPayId, false) },
                                                    FormMethod.Post, new { autocomplete = "off" }))
                                                {
                                                    <div class="row">
                                                        <div class="col-8">
                                                            <div class="form-group">
                                                                <input type="text" name="PayDate" class="form-control form-control-sm"
                                                                       placeholder="TDS Pay Date" value="" required data-mask />
                                                            </div>
                                                        </div>
                                                        <div class="col-4">
                                                            <button type="submit" class="btn btn-success"><i class="fas fa-save"></i> Paid</button>
                                                        </div>
                                                        <div class="d-none">
                                                            <input type="hidden" name="TDSPayId" value="@Model._tDSPays[i].TDSPayId" />
                                                        </div>
                                                    </div>
                                                }
                                            </td>
                                            <td>
                                                <strong>@Model._tDSPays[i].CompanyName</strong>
                                                <br />
                                                @Model._tDSPays[i].CompanyType
                                            </td>
                                            <td>
                                                @Model._tDSPays[i].PANNumber
                                            </td>
                                            <td>
                                                @if (Model._tDSPays[i].IsGSTRegistered)
                                                {
                                                    @Model._tDSPays[i].GSTNumber<br />
                                                    @Model._state[Model._tDSPays[i].GSTStateCode]
                                                }
                                                else
                                                {
                                                    <span class="right badge badge-danger">Unregistered</span>
                                                }
                                            </td>
                                            <td>
                                                @(Model._tDSPays[i].TDSPercentage != null ? Model._tDSPays[i].TDSPercentage.Value.ToDisplayDecimal() : string.Empty)%
                                                <br />
                                                @(Model._config.CurrencySymbol + Model._tDSPays[i].TDSAmount.ToDisplayDecimal())
                                            </td>
                                            <td>
                                                @(Model._config.CurrencySymbol + Model._tDSPays[i].PayAmount.ToDisplayDecimal())
                                                <br />
                                                @(Model._config.CurrencySymbol + Model._tDSPays[i].TotalAmount.ToDisplayDecimal())
                                            </td>
                                            <td>
                                                @(Model._tDSPays[i].PaymentDate.ToShortDateString())
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/JicoDotNet.Inventory.UI/Views/TDS/Receive.cshtml
@using JicoDotNet.Inventory.UI.Models;
@model TDSModels

@{
    ViewBag.Title = "Customer's TDS Receive";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>TDS from Customer</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item active"><a href="@Url.Action("Receive", "TDS")">TDS</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">TDS List (unreceived)</h3>
                    </div>
                    <div class="card-body table-responsive" style="overflow-x:scroll">
                        <table class="table table-striped table-bordered dt-responsive nowrap" data-table="normal">
                            <thead style="border-top: 1px solid #dee2e6;">
                                <tr>
                                    <th>Action</th>
                                    <th>Customer Name & Type</th>
                                    <th>PAN Number</th>
                                    <th>GST Number</th>
                                    <th>TDS</th>
                                    <th>Receive Amount</th>
                                    <th>Payment <br />Receive Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model._tDSReceives != null)
                                {
                                    for (int i = 0; i < Model._tDSReceives.Count; i++)
                                    {
                                        <tr>
                                            <td class="d-none">#@(i + 1)</td>
                                            <td style="min-width: 200px;">
                                                @using (Html.BeginForm("Receive", "TDS", new { id = Html.UrlIdEncrypt(Model._tDSReceives[i].TDSReceiveId, false) },
                                                    FormMethod.Post, new { autocomplete = "off" }))
                                                {
                                                    <div class="row">
                                                        <div class="col-8">
                                                            <div class="form-group">
                                                                <input type="text" name="ReceivedDate" class="form-control form-control-sm"
                                                                       placeholder="TDS Pay Date" value="" data-mask />
                                                            </div>
                                                        </div>
                                                        <div class="col-4">
                                                            <button type="submit" class="btn btn-warning"><i class="fas fa-save"></i> Receive</button>
                                                        </div>
                                                        <div class="d-none">
                                                            <input type="hidden" name="TDSReceiveId" value="@Model._tDSReceives[i].TDSReceiveId" />
                                                        </div>
                                                    </div>
                                                }
                                            </td>
                                            <td>
                                                <strong>@Model._tDSReceives[i].CompanyName</strong>
                                                <br />
                                                @Model._tDSReceives[i].CompanyType
                                            </td>
                                            <td>
                                                @Model._tDSReceives[i].PANNumber
                                            </td>
                                            <td>
                                                @if (Model._tDSReceives[i].IsGSTRegistered)
                                                {
                                                    @Model._tDSReceives[i].GSTNumber<br />
                                                    @Model._state[Model._tDSReceives[i].GSTStateCode]
                                                }
                                                else
                                                {
                                                    <span class="right badge badge-danger">Unregistered</span>
                                                }
                                            </td>
                                            <td>
                                                @(Model._tDSReceives[i].TDSPercentage != null ? Model._tDSReceives[i].TDSPercentage.Value.ToDisplayDecimal() : string.Empty)%
                                                <br />
                                                @(Model._config.CurrencySymbol + Model._tDSReceives[i].TDSAmount.ToDisplayDecimal())
                                            </td>
                                            <td>
                                                @(Model._config.CurrencySymbol + Model._tDSReceives[i].ReceiveAmount.ToDisplayDecimal())
                                                <br />
                                                @(Model._config.CurrencySymbol + Model._tDSReceives[i].TotalAmount.ToDisplayDecimal())
                                            </td>
                                            <td>
                                                @(Model._tDSReceives[i].PaymentDate.ToShortDateString())
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>