src/JicoDotNet.Inventory.UI/Areas/Report/Controllers/SalesController.cs
using JicoDotNet.Inventory.BusinessLayer.BLL;
using JicoDotNet.Inventory.BusinessLayer.BLL.Report;
using JicoDotNet.Inventory.Core.Report;
using JicoDotNet.Inventory.UI.Report.Models;
using System;
using System.Web.Mvc;
using JicoDotNet.Inventory.Controllers;

namespace JicoDotNet.Inventory.UI.Areas.Report.Controllers
{
    public class SalesController : BaseController
    {
        [SessionAuthenticate]
        public ActionResult Customer()
        {
            try
            {
                CustomerLogic customerLogic = new CustomerLogic(LogicHelper);
                SalesReportModels salesReportModels = new SalesReportModels
                {
                    _customerTypes = customerLogic.TypeGet(),
                    _customers = customerLogic.GetNonRetail()
                };
                return View(salesReportModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public PartialViewResult Customer(RequestCustomerSalesParam customerSales)
        {
            try
            {
                if (customerSales.SearchDate.IsInOneYearRange)
                {
                    SalesReportLogic salesReport = new SalesReportLogic(LogicHelper);
                    SalesReportModels salesReportModels = new SalesReportModels
                    {
                        _rCustomerSales = salesReport.CustomerWise(customerSales)
                    };
                    return PartialView("_PartialCustomerSales", salesReportModels);
                }
                else
                {
                    return PartialView("_PartialDateRangeMismatch", customerSales.SearchDate);
                }
            }
            catch (Exception ex)
            {
                return ErrorLoggingToPartial(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult Product()
        {
            try
            {
                ProductLogic productLogic = new ProductLogic(LogicHelper);
                SalesReportModels salesReportModels = new SalesReportModels
                {
                    _productTypes = productLogic.TypeGet(),
                    _products = productLogic.GetOut()
                };
                return View(salesReportModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public PartialViewResult Product(RequestProductSalesParam productSales)
        {
            try
            {
                if (productSales.SearchDate.IsInOneYearRange)
                {
                    SalesReportLogic salesReport = new SalesReportLogic(LogicHelper);
                    SalesReportModels salesReportModels = new SalesReportModels
                    {
                        _rProductSales = salesReport.ProductWise(productSales)
                    };
                    return PartialView("_PartialProductSales", salesReportModels);
                }
                else
                {
                    return PartialView("_PartialDateRangeMismatch", productSales.SearchDate);
                }
            }
            catch (Exception ex)
            {
                return ErrorLoggingToPartial(ex);
            }
        }
    }
}

src/JicoDotNet.Inventory.UI/Controllers/CustomerController.cs
using JicoDotNet.Inventory.BusinessLayer.BLL;
using JicoDotNet.Inventory.Core.Models;
using JicoDotNet.Inventory.UI.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using JicoDotNet.Inventory.Controllers;

namespace JicoDotNet.Inventory.UI.Controllers
{
    [SessionAuthenticate]
    public class CustomerController : BaseController
    {
        #region Customer Type
        [SessionAuthenticate]
        public ActionResult Type()
        {
            try
            {
                CustomerModels customerModels = new CustomerModels()
                {
                    _customerTypes = new CustomerLogic(LogicHelper).TypeGet()
                };
                if (!string.IsNullOrEmpty(UrlParameterId))
                {
                    customerModels._customerType = customerModels._customerTypes.Where(a => a.CustomerTypeId == Convert.ToInt64(UrlParameterId)).FirstOrDefault();
                }
                return View(customerModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult Type(CustomerType customerType)
        {
            try
            {
                customerType.CustomerTypeId = UrlParameterId == null ? 0 : Convert.ToInt64(UrlParameterId);

                #region Data Tracking...
                DataTrackingLogicSet(customerType);
                #endregion

                CustomerLogic customerLogic = new CustomerLogic(LogicHelper);
                if (Convert.ToInt64(customerLogic.TypeSet(customerType)) > 0)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Success",
                        Status = true
                    };
                }
                else
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Unsuccess",
                        Status = false
                    };
                }

                return RedirectToAction("Type", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public JsonResult TypeDeactivate(string Context)
        {
            try
            {
                if (new LoginManagement(LogicHelper).Authenticate(SessionPerson.UserEmail, Context))
                {
                    CustomerLogic customerTypeLogic = new CustomerLogic(LogicHelper);
                    if (Convert.ToInt64(customerTypeLogic.TypeDeactive(UrlParameterId)) > 0)
                        return Json(UrlParameterId, JsonRequestBehavior.AllowGet);
                    else
                        return Json(0, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(-1, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToJson(ex);
            }
        }
        #endregion

        #region Customer
        public ActionResult Index()
        {
            try
            {
                CustomerLogic customerLogic = new CustomerLogic(LogicHelper);
                CustomerModels customerModels = new CustomerModels()
                {
                    _customers = customerLogic.GetNonRetail(),
                    _customerTypes = customerLogic.TypeGet(true).ToList(),
                    _companyType = GenericLogic.CompanyType(),
                    _state = GenericLogic.State(),
                    _YesNo = GenericLogic.YesNo(),
                    IsRetail = false
                };
                if (!string.IsNullOrEmpty(UrlParameterId))
                {
                    customerModels._customer = customerModels._customers.Where(a => a.CustomerId == Convert.ToInt64(UrlParameterId)).FirstOrDefault();
                }
                return View(customerModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult Index(Customer customer)
        {
            try
            {
                customer.CustomerId = UrlParameterId == null ? 0 : Convert.ToInt64(UrlParameterId);

                #region Data Tracking...
                DataTrackingLogicSet(customer);
                #endregion

                CustomerLogic customerLogic = new CustomerLogic(LogicHelper);
                if (Convert.ToInt64(customerLogic.Set(customer)) > 0)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Success",
                        Status = true
                    };
                }
                else
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Unsuccess",
                        Status = false
                    };
                }

                return RedirectToAction("Index", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public JsonResult Deactivate(string Context)
        {
            try
            {
                if (new LoginManagement(LogicHelper).Authenticate(SessionPerson.UserEmail, Context))
                {
                    CustomerLogic customerLogic = new CustomerLogic(LogicHelper);
                    long deactivateId = Convert.ToInt64(customerLogic.Deactive(UrlParameterId));
                    return Json(new JsonReturnModels
                    {
                        _isSuccess = true,
                        _returnObject = deactivateId > 0 ? UrlParameterId : "0"
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new JsonReturnModels
                    {
                        _isSuccess = true,
                        _returnObject = "-1"
                    }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ErrorLogging(ex);
                throw ex;
            }
        }

        [SessionAuthenticate]
        public ActionResult Retail()
        {
            try
            {
                CustomerLogic customerLogic = new CustomerLogic(LogicHelper);
                CustomerModels customerModels = new CustomerModels()
                {
                    _customers = customerLogic.GetRetail(),
                    _customerTypes = customerLogic.TypeGet(true).ToList(),
                    _companyType = GenericLogic.CompanyType(),
                    _state = GenericLogic.State(),
                    _YesNo = GenericLogic.YesNo(),
                    IsRetail = true
                };
                if (!string.IsNullOrEmpty(UrlParameterId))
                {
                    customerModels._customer = customerModels._customers.Where(a => a.CustomerId == Convert.ToInt64(UrlParameterId)).FirstOrDefault();
                }
                return View("Index", customerModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        [SessionAuthenticate]
        public ActionResult Retail(Customer customer)
        {
            try
            {
                customer.CustomerId = UrlParameterId == null ? 0 : Convert.ToInt64(UrlParameterId);

                #region Data Tracking...
                DataTrackingLogicSet(customer);
                #endregion

                CustomerLogic customerLogic = new CustomerLogic(LogicHelper);
                if (Convert.ToInt64(customerLogic.Set(customer)) > 0)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Success",
                        Status = true
                    };
                }
                else
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Unsuccess",
                        Status = false
                    };
                }
                return RedirectToAction("Retail", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }
        #endregion
    }
}

src/JicoDotNet.Inventory.UI/Areas/Report/Views/Sales/Customer.cshtml
@using JicoDotNet.Inventory.UI.Report.Models;
@using JicoDotNet.Inventory.Core.Models
@model SalesReportModels

@{
    ViewBag.Title = "Customer wise sales report";
    ViewBag.Page = "/Report/Sales/Customer";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Customer wise report</h1>
            </div>
            <div class="col-sm-6 d-none d-sm-block">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Report</a></li>
                    <li class="breadcrumb-item active">By Customer</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">
                            Search Details
                        </h3>
                    </div>
                    <form id="formSearch" autocomplete="off" action="#">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <span class="text-center text-primary">
                                        This report is based on generated Invoice for your customer.
                                    </span>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Start Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="StartDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.AddMonths(-1).ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>End Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="EndDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Customer Type</label>
                                        <select class="form-control form-control-sm" name="CustomerTypeId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._customerTypes != null)
                                            {
                                                foreach (CustomerType customerType in Model._customerTypes)
                                                {
                                                    <option value="@customerType.CustomerTypeId">
                                                        @customerType.CustomerTypeName @(!customerType.IsActive ? " - Inactive" : string.Empty)
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Customer</label><br />
                                        <select class="form-control form-control-sm select2" name="CustomerId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._customers != null)
                                            {
                                                foreach (Customer customer in Model._customers)
                                                {
                                                    <option value="@customer.CustomerId">
                                                        @customer.CompanyName - @(customer.IsGSTRegistered ? customer.GSTNumber : "GST Unregistred")
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Retail /Non-retail</label>
                                        <select class="form-control form-control-sm" name="ForRetail">
                                            <option value="">All</option>
                                            <option value="true">Only Retail</option>
                                            <option value="false">Only Non-Retail</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary"> <i class="fas fa-search"></i> Search </button>
                            <button type="reset" class="btn btn-info"><i class="fas fa-sync"></i> Reset</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">Sales Details</h3>
                    </div>
                    <div class="card-body table-responsive" data-report>
                        <p class="text-center mb-0 m-2">Search to get your reports</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section BodyScript{
    <script type="text/javascript">
        $(document).ready(function () {
            $('form#formSearch').submit(function (e) {
                e.preventDefault();
                var eThis = this;
                var data = {
                    SearchDate: {
                        StartDate: $(this).find('input[name="StartDate"]').val(),
                        EndDate: $(this).find('input[name="EndDate"]').val(),
                    },
                    CustomerId: $(this).find('select[name="CustomerId"]').val(),
                    CustomerTypeId: $(this).find('select[name="CustomerTypeId"]').val(),
                    ForRetail: $(this).find('select[name="ForRetail"]').val()
                };
                $('[data-table="report"]').html('<div class="overlay text-center m-4"><i class="fas fa-sync-alt fa-spin fa-2x"></i></div>');
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Customer", "Sales", new { Area = "Report" })",
                    data: JSON.stringify(data),
                    contentType: "application/json; charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        $('[data-report]').html(data);
                        setDefaultButton(eThis);
                        loadDatatable();
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    }
                });
                return false;
            });
        });
    </script>
}

src/JicoDotNet.Inventory.UI/Areas/Report/Views/Sales/Product.cshtml
@using JicoDotNet.Inventory.UI.Report.Models;
@using JicoDotNet.Inventory.Core.Models
@model SalesReportModels

@{
    ViewBag.Title = "Product wise sales report";
    ViewBag.Page = "/Report/Sales/Product";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Product wise sales report</h1>
            </div>
            <div class="col-sm-6 d-none d-sm-block">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Report</a></li>
                    <li class="breadcrumb-item active">By Product</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">
                            Search Details
                        </h3>
                    </div>
                    <form id="formSearch" autocomplete="off" action="#">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <span class="text-center text-primary">
                                        This report is based on generated Invoice for your customer.
                                    </span>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Start Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="StartDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.AddMonths(-1).ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>End Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="EndDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Product Type</label>
                                        <select class="form-control form-control-sm" name="ProductTypeId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._productTypes != null)
                                            {
                                                foreach (ProductType productType in Model._productTypes)
                                                {
                                                    <option value="@productType.ProductTypeId">
                                                        @productType.ProductTypeName @(!productType.IsActive ? " - Inactive" : string.Empty)
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Product</label><br />
                                        <select class="form-control form-control-sm select2" name="ProductId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._products != null)
                                            {
                                                foreach (Product product in Model._products)
                                                {
                                                    <option value="@product.ProductId">
                                                        @product.ProductName @(string.IsNullOrEmpty(product.ProductCode) ? string.Empty : " - " + product.ProductCode)
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Retail /Non-retail</label>
                                        <select class="form-control form-control-sm" name="ForRetail">
                                            <option value="">All</option>
                                            <option value="true">Only Retail</option>
                                            <option value="false">Only Non-Retail</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary"> <i class="fas fa-search"></i> Search </button>
                            <button type="reset" class="btn btn-info"><i class="fas fa-sync"></i> Reset</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">Sales Details</h3>
                    </div>
                    <div class="card-body table-responsive" data-report>
                        <p class="text-center mb-0 m-2">Search to get your reports</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section BodyScript{
    <script type="text/javascript">
        $(document).ready(function(){
            $('form#formSearch').submit(function (e) {
                e.preventDefault();
                var eThis = this;
                var data = {
                    SearchDate: {
                        StartDate: $(this).find('input[name="StartDate"]').val(),
                        EndDate: $(this).find('input[name="EndDate"]').val(),
                    },
                    ProductId: $(this).find('select[name="ProductId"]').val(),
                    ProductTypeId: $(this).find('select[name="ProductTypeId"]').val(),
                    ForRetail: $(this).find('select[name="ForRetail"]').val()
                };
                $('[data-table="report"]').html('<div class="overlay text-center m-4"><i class="fas fa-sync-alt fa-spin fa-2x"></i></div>');
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Product", "Sales", new { Area = "Report" })",
                    data: JSON.stringify(data),
                    contentType: "application/json; charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        $('[data-report]').html(data);
                        setDefaultButton(eThis);
                        loadDatatable();
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    }
                });
                return false;
            });
        });
    </script>
}

src/JicoDotNet.Inventory.UI/Areas/Report/Views/Sales/_PartialCustomerSales.cshtml
@using JicoDotNet.Inventory.UI.Report.Models;
@using JicoDotNet.Inventory.Core.Report
@model SalesReportModels

<table class="table table-striped table-bordered dt-responsive nowrap" data-table="report">
    <thead>
        <tr>
            <th>Customer Name</th>
            <th>Mobile</th>
            <th>GST Number</th>
            <th>No of Invoice</th>
            <th>Invoice Amount</th>
            <th>Tax Amount</th>
            <th>Total Amount</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model._rCustomerSales != null)
        {
            foreach (ResponseCustomerSalesResult rCustomerSales in Model._rCustomerSales)
            {
                <tr>
                    <td>
                        @rCustomerSales.CompanyName
                    </td>
                    <td>
                        @rCustomerSales.Mobile
                    </td>
                    <td>
                        @if (rCustomerSales.IsGSTRegistered)
                        {
                            @rCustomerSales.GSTNumber
                        }
                        else
                        {
                            <text>Unregistered</text>
                        }
                    </td>
                    <td>
                        @rCustomerSales.TotalInvoiceCount
                    </td>
                    <td>
                        @rCustomerSales.SumInvoicedAmount.ToDisplayDecimal()
                    </td>
                    <td>
                        @rCustomerSales.SumTaxAmount.ToDisplayDecimal()
                    </td>
                    <td>
                        @rCustomerSales.SumTotalAmount.ToDisplayDecimal()
                    </td>
                </tr>
            }
        }
    </tbody>
</table>