src/JicoDotNet.Inventory.UI/Areas/Report/Controllers/PurchaseController.cs
using JicoDotNet.Inventory.BusinessLayer.BLL;
using JicoDotNet.Inventory.BusinessLayer.BLL.Report;
using JicoDotNet.Inventory.Core.Report;
using JicoDotNet.Inventory.UI.Report.Models;
using System;
using System.Web.Mvc;
using JicoDotNet.Inventory.Controllers;

namespace JicoDotNet.Inventory.UI.Areas.Report.Controllers
{
    public class PurchaseController : BaseController
    {
        [SessionAuthenticate]
        public ActionResult Vendor()
        {
            try
            {
                VendorLogic vendorLogic = new VendorLogic(LogicHelper);
                PurchaseReportModels purchaseReportModels = new PurchaseReportModels
                {
                    _vendorTypes = vendorLogic.TypeGet(),
                    _vendors = vendorLogic.Get()
                };
                return View(purchaseReportModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }
        [HttpPost]
        public PartialViewResult Vendor(RequestVendorPurchaseParam vendorPurchase)
        {
            try
            {
                if (vendorPurchase.SearchDate.IsInOneYearRange)
                {
                    PurchaseReportLogic purchaseReport = new PurchaseReportLogic(LogicHelper);
                    PurchaseReportModels salesReportModels = new PurchaseReportModels
                    {
                        _rVendorPurchase = purchaseReport.VendorWise(vendorPurchase)
                    };
                    return PartialView("_PartialVendorPurchase", salesReportModels);
                }
                else
                {
                    return PartialView("_PartialDateRangeMismatch", vendorPurchase.SearchDate);
                }
            }
            catch (Exception ex)
            {
                return ErrorLoggingToPartial(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult Product()
        {
            try
            {
                ProductLogic productLogic = new ProductLogic(LogicHelper);
                PurchaseReportModels salesReportModels = new PurchaseReportModels
                {
                    _productTypes = productLogic.TypeGet(),
                    _products = productLogic.GetIn()
                };
                return View(salesReportModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public PartialViewResult Product(RequestProductPurchaseParam productPurchase)
        {
            try
            {
                if (productPurchase.SearchDate.IsInOneYearRange)
                {
                    PurchaseReportLogic salesReport = new PurchaseReportLogic(LogicHelper);
                    PurchaseReportModels salesReportModels = new PurchaseReportModels
                    {
                        _rProductPurchase = salesReport.ProductWise(productPurchase)
                    };
                    return PartialView("_PartialProductPurchase", salesReportModels);
                }
                else
                {
                    return PartialView("_PartialDateRangeMismatch", productPurchase.SearchDate);
                }
            }
            catch (Exception ex)
            {
                return ErrorLoggingToPartial(ex);
            }
        }
    }
}

src/JicoDotNet.Inventory.UI/Controllers/ProductController.cs
using JicoDotNet.Inventory.BusinessLayer.BLL;
using JicoDotNet.Inventory.Core.Entities;
using JicoDotNet.Inventory.Core.Models;
using JicoDotNet.Inventory.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using JicoDotNet.Inventory.Controllers;
using DataAccess.AzureStorage.Blob;
using System.IO;
using System.Web;

namespace JicoDotNet.Inventory.UI.Controllers
{
    public class ProductController : BaseController
    {
        [SessionAuthenticate]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult PartialIndex()
        {
            try
            {
                ProductModels productModels = new ProductModels()
                {
                    _products = new ProductLogic(LogicHelper).Get()
                };
                return PartialView("_PartialIndex", productModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToPartial(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult Add()
        {
            try
            {
                if (string.IsNullOrEmpty(UrlParameterId))
                {
                    // Limit Quota Checking
                    ProductModels productModels = new ProductModels()
                    {
                        _productTypes = new ProductLogic(LogicHelper).TypeGet().Where(a => a.IsActive).ToList(),
                        _unitOfMeasures = new UnitOfMeasureLogic(LogicHelper).Get().Where(a => a.IsActive).ToList(),
                        _YesNo = GenericLogic.YesNo(),
                        _ProductCategory = GenericLogic.ProductCategory(),
                        _config = new ConfigarationManager(LogicHelper).GetConfig()
                    };
                    return View(productModels);
                }
                return RedirectToAction("Index", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult Edit()
        {
            try
            {
                if (!string.IsNullOrEmpty(UrlParameterId))
                {
                    ProductModels productModels = new ProductModels()
                    {
                        _productTypes = new ProductLogic(LogicHelper).TypeGet().Where(a => a.IsActive).ToList(),
                        _unitOfMeasures = new UnitOfMeasureLogic(LogicHelper).Get().Where(a => a.IsActive).ToList(),
                        _YesNo = GenericLogic.YesNo(),
                        _ProductCategory = GenericLogic.ProductCategory(),
                        _config = new ConfigarationManager(LogicHelper).GetConfig(),
                        _product = new ProductLogic(LogicHelper).Get().FirstOrDefault(a => a.ProductId == Convert.ToInt64(UrlParameterId))
                    };
                    return View("Add", productModels);
                }
                return RedirectToAction("Index", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult Add(Product product, bool HaveOpeningStock = false)
        {
            try
            {
                product.ProductId = UrlParameterId == null ? 0 : Convert.ToInt64(UrlParameterId);

                #region Data Tracking...
                DataTrackingLogicSet(product);
                #endregion

                ProductLogic productLogic = new ProductLogic(LogicHelper);

                #region Image Upload
                if (Request.Files.Count > 0)
                {
                    if (Request.Files["ProductImageUrl"] != null)
                    {
                        HttpPostedFileBase file = Request.Files["ProductImageUrl"];

                        if (file != null && file.ContentLength > 0)
                        {
                            Stream fileStream = file.InputStream;
                        }
                        IBlobRequestClient blobRequest = new BlobRequestClient(file.InputStream, LogicHelper.RequestId + file.FileName);
                        product.ProductImageUrl = productLogic.UploadImage(blobRequest).Path;
                    }
                }
                    
                        
                #endregion
                long PId = Convert.ToInt64(productLogic.Set(product));
                if (PId > 0)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Success",
                        Status = true
                    };
                }
                else
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Unsuccess",
                        Status = false
                    };
                }
                if (HaveOpeningStock)
                    return RedirectToAction("OpeningStock", new { id = UrlIdEncrypt(PId, false) });
                return RedirectToAction("Index", new { id = string.Empty });
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public JsonResult Deactivate(string Context)
        {
            try
            {
                if (new LoginManagement(LogicHelper).Authenticate(SessionPerson.UserEmail, Context))
                {
                    ProductLogic productLogic = new ProductLogic(LogicHelper);
                    long deactivateId = Convert.ToInt64(productLogic.Deactivate(UrlParameterId));
                    return Json(new JsonReturnModels
                    {
                        _isSuccess = true,
                        _returnObject = deactivateId > 0 ? UrlParameterId : "0"
                    }, JsonRequestBehavior.AllowGet);
                }

                return Json(new JsonReturnModels
                {
                    _isSuccess = true,
                    _returnObject = "-1"
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToJson(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult OpeningStock()
        {
            try
            {
                if (string.IsNullOrEmpty(UrlParameterId))
                    return RedirectToAction("Index");

                ProductModels productModels = new ProductModels();
                if (new StockLogic(LogicHelper).TotalNonOpeningStockQuantity(Convert.ToInt64(UrlParameterId)) == 0)
                {
                    productModels._product = new ProductLogic(LogicHelper).Get(true)
                        .FirstOrDefault(a => a.ProductId == Convert.ToInt64(UrlParameterId) && a.IsGoods);
                    productModels._wareHouses = new WareHouseLogic(LogicHelper).Get(true);
                }
                return View(productModels);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        [HttpPost]
        public ActionResult OpeningStock(List<StockDetail> stockDetails)
        {
            try
            {
                if (Convert.ToInt64(new StockLogic(LogicHelper).AddOpeningStock(stockDetails, Convert.ToInt64(UrlParameterId))) > 0)
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Opening Stock Entry Successful",
                        Status = true
                    };
                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    ReturnMessage = new ReturnObject()
                    {
                        Message = "Unsuccess",
                        Status = false
                    };
                }
                return RedirectToAction("OpeningStock");
            }
            catch (Exception ex)
            {
                return ErrorLoggingToView(ex);
            }
        }

        public PartialViewResult AddOpeningStock(bool HasBatchNo,
            bool HasExpirationDate,
            bool IsPerishableProduct,
            string UnitOfMeasureName, long WareHouseId, int len)
        {
            try
            {
                Product product = new Product()
                {
                    HasBatchNo = HasBatchNo,
                    HasExpirationDate = HasExpirationDate,
                    IsPerishableProduct = IsPerishableProduct,
                    UnitOfMeasureName = UnitOfMeasureName,
                    ProductName = WareHouseId.ToString(),   // This is Temp using to excape extra memory using.
                    ProductId = len                         // This is Temp using to excape extra memory using.
                };
                return PartialView("_PartialOpeningStock", product);
            }
            catch (Exception ex)
            {
                return ErrorLoggingToPartial(ex);
            }
        }

        [SessionAuthenticate]
        public ActionResult BulkOpeningStock()
        {
            try
            {
                if (string.IsNullOrEmpty(UrlParameterId))
                    return RedirectToAction("Index");

                ProductModels productModels = new ProductModels();
                if (new StockLogic(LogicHelper).TotalNonOpeningStockQuantity(Convert.ToInt64(UrlParameterId)) == 0)
                {
                    productModels._product = new ProductLogic(LogicHelper).Get(true)
                        .FirstOrDefault(a => a.ProductId == Convert.ToInt64(UrlParameterId) && a.IsGoods);

src/JicoDotNet.Inventory.UI/Areas/Report/Views/Purchase/Product.cshtml
@using JicoDotNet.Inventory.UI.Report.Models;
@using JicoDotNet.Inventory.Core.Models
@model PurchaseReportModels

@{
    ViewBag.Title = "Product wise purchase report";
    ViewBag.Page = "/Report/Purchase/Product";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Product wise purchase report</h1>
            </div>
            <div class="col-sm-6 d-none d-sm-block">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home", new { Area = "Report" }))">Report</a></li>
                    <li class="breadcrumb-item active">By Product</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">
                            Search Details
                        </h3>
                    </div>
                    <form id="formSearch" autocomplete="off" action="#">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <span class="text-center text-primary">
                                        This report is based on generated Bill for your Vendor.
                                    </span>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Start Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="StartDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.AddMonths(-1).ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>End Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="EndDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Product Type</label>
                                        <select class="form-control form-control-sm" name="ProductTypeId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._productTypes != null)
                                            {
                                                foreach (ProductType productType in Model._productTypes)
                                                {
                                                    <option value="@productType.ProductTypeId">
                                                        @productType.ProductTypeName @(!productType.IsActive ? " - Inactive" : string.Empty)
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Product</label><br />
                                        <select class="form-control form-control-sm select2" name="ProductId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._products != null)
                                            {
                                                foreach (Product product in Model._products)
                                                {
                                                    <option value="@product.ProductId">
                                                        @product.ProductName @(string.IsNullOrEmpty(product.ProductCode) ? string.Empty : " - " + product.ProductCode)
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary"> <i class="fas fa-search"></i> Search </button>
                            <button type="reset" class="btn btn-info"><i class="fas fa-sync"></i> Reset</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">Sales Details</h3>
                    </div>
                    <div class="card-body table-responsive" data-report>
                        <p class="text-center mb-0 m-2">Search to get your reports</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section BodyScript{
    <script type="text/javascript">
        $(document).ready(function () {
            $('form#formSearch').submit(function (e) {
                e.preventDefault();
                var eThis = this;
                var data = {
                    SearchDate: {
                        StartDate: $(this).find('input[name="StartDate"]').val(),
                        EndDate: $(this).find('input[name="EndDate"]').val(),
                    },
                    ProductId: $(this).find('select[name="ProductId"]').val(),
                    ProductTypeId: $(this).find('select[name="ProductTypeId"]').val()
                };
                $('[data-table="report"]').html('<div class="overlay text-center m-4"><i class="fas fa-sync-alt fa-spin fa-2x"></i></div>');
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Product", "Purchase", new { Area = "Report" })",
                    data: JSON.stringify(data),
                    contentType: "application/json; charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        $('[data-report]').html(data);
                        setDefaultButton(eThis);
                        loadDatatable();
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    }
                });
                return false;
            });
        });
    </script>
}

src/JicoDotNet.Inventory.UI/Areas/Report/Views/Purchase/Vendor.cshtml
@using JicoDotNet.Inventory.UI.Report.Models;
@using JicoDotNet.Inventory.Core.Models
@model PurchaseReportModels

@{
    ViewBag.Title = "Vendor wise purchase report";
    ViewBag.Page = "/Report/Purchase/Vendor";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Vendor wise report</h1>
            </div>
            <div class="col-sm-6 d-none d-sm-block">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home", new { Area = "Report" })">Report</a></li>
                    <li class="breadcrumb-item active">By Vendor</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">
                            Search Details
                        </h3>
                    </div>
                    <form id="formSearch" autocomplete="off" action="#">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <span class="text-center text-primary">
                                        This report is based on generated Bill for your vendor.
                                    </span>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Start Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="StartDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.AddMonths(-1).ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>End Date</label>
                                        <small>Day/Month/Year</small>
                                        <input type="text" name="EndDate" class="form-control form-control-sm" required
                                               placeholder="Search Date" data-mask readonly
                                               value="@GenericLogic.IstNow.ToDateMaskString()" />
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Vendor Type</label>
                                        <select class="form-control form-control-sm" name="VendorTypeId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._vendorTypes != null)
                                            {
                                                foreach (VendorType vendorType in Model._vendorTypes)
                                                {
                                                    <option value="@vendorType.VendorTypeId">
                                                        @vendorType.VendorTypeName @(!vendorType.IsActive ? " - Inactive" : string.Empty)
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Vendor</label><br />
                                        <select class="form-control form-control-sm select2" name="VendorId">
                                            <option value="">-- Select --</option>
                                            @if (Model != null && Model._vendors != null)
                                            {
                                                foreach (Vendor vendor in Model._vendors)
                                                {
                                                    <option value="@vendor.VendorId">
                                                        @vendor.CompanyName - @(vendor.IsGSTRegistered ? vendor.GSTNumber : "GST Unregistred")
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <!--<div class="form-group">
            <label>Retail /Non-retail</label>
            <select class="form-control form-control-sm" name="ForRetail">
                <option value="">All</option>
                <option value="true">Only Retail</option>
                <option value="false">Only Non-Retail</option>
            </select>
        </div>-->
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary"> <i class="fas fa-search"></i> Search </button>
                            <button type="reset" class="btn btn-info"><i class="fas fa-sync"></i> Reset</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header bg-cyan">
                        <h3 class="card-title">Sales Details</h3>
                    </div>
                    <div class="card-body table-responsive" data-report>
                        <p class="text-center mb-0 m-2">Search to get your reports</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section BodyScript{
    <script type="text/javascript">
        $(document).ready(function () {
            $('form#formSearch').submit(function (e) {
                e.preventDefault();
                var eThis = this;
                var data = {
                    SearchDate: {
                        StartDate: $(this).find('input[name="StartDate"]').val(),
                        EndDate: $(this).find('input[name="EndDate"]').val(),
                    },
                    VendorId: $(this).find('select[name="VendorId"]').val(),
                    VendorTypeId: $(this).find('select[name="VendorTypeId"]').val()
                };
                $('[data-table="report"]').html('<div class="overlay text-center m-4"><i class="fas fa-sync-alt fa-spin fa-2x"></i></div>');
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Vendor", "Purchase", new { Area = "Report" })",
                    data: JSON.stringify(data),
                    contentType: "application/json; charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        $('[data-report]').html(data);
                        setDefaultButton(eThis);
                        loadDatatable();
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                        setDefaultButton(eThis);
                    }
                });
                return false;
            });
        });
    </script>
}